name: SBOM

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  sbom:
    name: Generate SBOM
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
        with:
          persist-credentials: false

      - name: Generate SBOM
        uses: anchore/sbom-action@bb716408e75840bbb01e839347cd213767269d4a
        with:
          path: .
          artifact-name: sbom.spdx.json
          format: spdx-json
          dependency-snapshot: true
