name: Format

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened

permissions:
  contents: write

jobs:
  format:
    name: Format code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
      - name: Install dependencies
        run: yarn install --frozen-lockfile --ignore-scripts

      - name: Format
        run: yarn prettier --write "lib/**/*.js" "test/**/*.js"

      - name: Commit formatting changes
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "style: format with Prettier"
          branch: ${{ github.head_ref }}
